### ISSUE TITLE
Dependency on Phython 3.0 ERROR. Plugin , the master and the testing not installable Leia 18.9 FIX?

### ISSUE THREAD

**Issue by vigilant4u** [winsomehax/KODI-DLIVE-plugin#12]
Dependency on Phython 3.0 ERROR. Plugin , the master and the testing not installable Leia 18.9 FIX?

**Comment by winsomehax** [comment]
try it again

**Comment by vigilant4u** [comment]
> try it again

already did. a couple of times. does not work:

2021-01-07 12:41:30.302 T:123145370284032   ERROR: CAddonInstallJob[plugin.video.dlive]: Die Abhängigkeit auf xbmc.python in Version 3.0.0 konnte nicht aufgelöst werden.

**Comment by winsomehax** [comment]
You will need to download a new zip copy of it and try again.

**Comment by vigilant4u** [comment]
> You will need to download a new zip copy of it and try again.

ok. sorry. i did. now i was able to install but: THERE IS NO LOGIN Possibility. I can only chose my Name. Any solutions?

**Comment by vigilant4u** [comment]
> > You will need to download a new zip copy of it and try again.
> 
> ok. sorry. i did. now i was able to install but: THERE IS NO LOGIN Possibility. I can only chose my Name. Any solutions?

ok. Just recognized that by just typing my username my followers are displayed. how does that work. Anyway. I can live with it. Thx again for support ;)

**Comment by winsomehax** [comment]
On the main page:

https://github.com/winsomehax/KODI-DLIVE-plugin

I give a quick explanation of why you don't need to login, rather you just provide your display name. It's because who you follow on DLIVE is public... so to get that list, the add-on doesn't need to login as you. It just needs to know your display name.
