### ISSUE TITLE
kodi_dlive.py missing

### ISSUE THREAD

**Issue by s644** [winsomehax/KODI-DLIVE-plugin#2]
Hi,
[https://github.com/winsomehax/KODI-DLIVE-plugin/commit/3163ca7e641e0ea22d11da0a34ce40f71b372f5e#diff-5bc02cefb3ea9e27f1a6776eabd1935d](url)

imho in this commit, you forgot to move the removed stuff to a new file called kodi_dlive.py.
Withoud kodi_dlive.py the plugin doesn't run ;) I created the file in my kodi/addon/plugin.video.dlive folder and it runs fine now.

**Comment by winsomehax** [comment]
You're right.. I missed committing and pushing kodi_dlive.py. Thanks for letting me know. Good to know someone is getting use out of it. I've downloaded the zip version and installed it myself and it seems to be working now. 

Thanks again.
